services:
  db:
    image: mongo
    restart: always 
    ports:
      - 27017:27017
    environment:
       MONGODB_DATABASE: nest-course
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - ./init-replica.js:/docker-entrypoint-initdb.d/init-replica.js:ro
